project:
  type: website

website:
  title: ""
  navbar:
    background: transparent
    left:
      - text: Home
        href: index.qmd
      - text: Education & Experience
        href: about.qmd
      - text: Projects
        href: projects.qmd
    right:
      - icon: github
        href: https://github.com/zainnofal
      - icon: linkedin
        href: https://linkedin.com/in/zainnofal

format:
  html:
    css: styles.css
    toc: false
