project:
  type: website
  output-dir: docs

website:
  title: "Zain Nofal"
  navbar:
    right:
      - about.qmd
      - projects.qmd
      - index.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



